### ISSUE TITLE
 bundling failed: Error: Couldn't find preset "env" relative to directory

### ISSUE THREAD

**Issue by khorark** [TBingooo/react-native-adaptive-stylesheet#1]
Hi. 

I have this error  

> bundling failed: Error: Couldn't find preset "env" relative to directory "*\\node_modules\\react-native-adaptive-stylesheet"

**Comment by TBingooo** [comment]
Hi, could you give a demo project to reproduce this error?

**Comment by TBingooo** [comment]
Hi. I can not reproduce this error, and due to the lack of response, I'd like to close this issue. Feel free to reopen it.
